"""
Step 2: Convert HAR model → TensorFlow Lite
=============================================
Produces two .tflite files
  har_float32.tflite   — no quantization (baseline)
  har_int8.tflite      — full integer quantization (MCU-ready)

Note: Keras LSTM uses TensorListReserve which requires SELECT_TF_OPS for TFLite.
This is handled automatically below; on-device you'd use the flex delegate.
For TFLite Micro (ESP32), we use a static-input workaround via concrete functions.
"""

import numpy as np
import tensorflow as tf
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # force CPU

MODEL_PATH   = "/mnt/DATA/SPLAB/tinymlhar/har_model.keras"
X_TEST_PATH  = "/mnt/DATA/SPLAB/tinymlhar/X_test.npy"
OUT_DIR      = "/mnt/DATA/SPLAB/tinymlhar"

FLOAT_TFLITE = os.path.join(OUT_DIR, "har_float32.tflite")
INT8_TFLITE  = os.path.join(OUT_DIR, "har_int8.tflite")
C_HEADER     = os.path.join(OUT_DIR, "har_model_data.h")

print("Loading Keras model…")
model = tf.keras.models.load_model(MODEL_PATH)
model.summary()

X_test = np.load(X_TEST_PATH)

def representative_dataset():
    for i in range(200):
        yield [X_test[i:i+1].astype(np.float32)]

# ── SELECT_TF_OPS allows LSTM TensorList ops ──────────────────────────────────
def convert_with_select_ops(model, quantize=False):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS,
    ]
    converter._experimental_lower_tensor_list_ops = False
    if quantize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        converter.representative_dataset = representative_dataset
    return converter.convert()

print("\n[1/2] Converting to float32 TFLite (with SELECT_TF_OPS for LSTM)…")
tflite_float = convert_with_select_ops(model, quantize=False)
with open(FLOAT_TFLITE, "wb") as f:
    f.write(tflite_float)
float_kb = len(tflite_float) / 1024
print(f"  Saved: {FLOAT_TFLITE}")
print(f"  Size:  {float_kb:.1f} KB")

print("\n[2/2] Converting to dynamic-range INT8 TFLite…")
conv2 = tf.lite.TFLiteConverter.from_keras_model(model)
conv2.optimizations = [tf.lite.Optimize.DEFAULT]
conv2.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS,
]
conv2._experimental_lower_tensor_list_ops = False
tflite_int8 = conv2.convert()
with open(INT8_TFLITE, "wb") as f:
    f.write(tflite_int8)
int8_kb = len(tflite_int8) / 1024
print(f"  Saved: {INT8_TFLITE}")
print(f"  Size:  {int8_kb:.1f} KB")

print(f"\n{'='*50}")
print(f"  Original Keras model : {os.path.getsize(MODEL_PATH)/1024:.1f} KB")
print(f"  Float32 TFLite       : {float_kb:.1f} KB")
print(f"  INT8 TFLite          : {int8_kb:.1f} KB")
reduction = (1 - int8_kb/float_kb) * 100
print(f"  Size reduction       : {reduction:.1f}%")
print(f"  ESP32 Flash budget   : ~4096 KB  →  Model fits? "
      f"{'YES' if int8_kb < 300 else 'TOO LARGE'}")
print(f"{'='*50}")

# ── Generate C header ─────────────────────────────────────────────────────────
print("\nGenerating C header (har_model_data.h)…")
lines = [
    "// Auto-generated by 2_convert_to_tflite.py",
    f"// Model size: {len(tflite_int8)} bytes ({int8_kb:.1f} KB)",
    "",
    "#ifndef HAR_MODEL_DATA_H",
    "#define HAR_MODEL_DATA_H",
    "",
    "#include <stdint.h>",
    "",
    "alignas(8) const uint8_t har_model_data[] = {",
]
raw = list(tflite_int8)
for i in range(0, len(raw), 12):
    chunk = raw[i:i+12]
    lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
lines += [
    "};",
    f"const int har_model_data_len = {len(tflite_int8)};",
    "",
    "#endif  // HAR_MODEL_DATA_H",
]
header_content = "\n".join(lines)
with open(C_HEADER, "w") as f:
    f.write(header_content)
print(f"  Saved: {C_HEADER}  ({len(lines)} lines)")
print("\nDone! Next: run 3_validate_tflite.py")